import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { createWallet, listWallets } from '@open-wallet-standard/core';

const DEFAULT_WALLET_ID = 'example-wallet';
const DEFAULT_PASSPHRASE = 'example-passphrase';

function examplePaths(rootDir) {
  const baseDir = resolve(rootDir);
  return {
    rootDir: baseDir,
    demoDir: join(baseDir, '.demo'),
    vaultPath: join(baseDir, '.demo', 'vault'),
    envPath: join(baseDir, '.env'),
    configPath: join(baseDir, 'mindpass.config.json'),
  };
}

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function writeIfChanged(path, content) {
  let previous = null;
  try {
    previous = readFileSync(path, 'utf8');
  } catch {}

  if (previous !== content) {
    writeFileSync(path, content, 'utf8');
  }
}

export async function setupExample(options = {}) {
  const paths = examplePaths(options.rootDir ?? process.cwd());
  ensureDir(paths.demoDir);
  ensureDir(paths.vaultPath);

  const existing = listWallets(paths.vaultPath);
  let wallet = existing.find((item) => item.id === DEFAULT_WALLET_ID || item.name === DEFAULT_WALLET_ID);
  if (!wallet) {
    wallet = createWallet(DEFAULT_WALLET_ID, DEFAULT_PASSPHRASE, 12, paths.vaultPath);
  }

  const envText =
    `# Auto-generated by examples/ows/scripts/setup.mjs\n` +
    `CONFIG_PATH=${paths.configPath}\n` +
    `OWS_PASSPHRASE=${DEFAULT_PASSPHRASE}\n`;

  const config = {
    walletId: DEFAULT_WALLET_ID,
    vaultPath: paths.vaultPath,
    policy: [
      {
        type: 'prefer-protocol',
        protocol: 'siwx',
        boost: 0.1,
      },
    ],
  };

  writeIfChanged(paths.envPath, envText);
  writeIfChanged(paths.configPath, JSON.stringify(config, null, 2) + '\n');

  return {
    ...paths,
    walletId: DEFAULT_WALLET_ID,
    passphrase: DEFAULT_PASSPHRASE,
    wallet,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = await setupExample();
  console.log(`OWS example ready.`);
  console.log(`Wallet: ${result.walletId}`);
  console.log(`Vault:  ${result.vaultPath}`);
  console.log(`Config: ${result.configPath}`);
  console.log(`Env:    ${result.envPath}`);
  console.log(`Run:    bun run start`);
}
